# Generated by Django 5.2.6 on 2025-09-25 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.CharField(default='', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=150)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('datetime', models.DateTimeField(default='2025-01-01 00:00:00')),
                ('description', models.CharField(default='', max_length=150)),
                ('card', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.card')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
