# Server Config
BUFFER_SIZE = 1024
IP = '127.0.0.1'
PORT = 8888
SEP = '<CMD_END>'

#region CMDs

# Authentication
CMD_AUTH = 'AUTH'
CMD_LOGOUT = 'LOGOUT'

# User
CMD_CREATE_USER = 'CREATE_USER'

# Profile
CMD_CREATE_PROFILE = 'CREATE_PROFILE'
CMD_GET_PROFILES = 'GET_PROFILES'
CMD_GET_ID_FROM_DEFAULT_PROFILE = 'GET_ID_FROM_DEFAULT_PROFILE'
CMD_UPDATE_DEF_PROFILE = 'UPDATE_DEF_PROFILE'
CMD_NO_PROFILE_FOUND = 'NO_PROFILE_FOUND'
CMD_PENDING_SHARE = 'PENDING_SHARE'
CMD_SHARE_PROFILE = 'SHARE_PROFILE'

# Third Parties
CMD_GET_PROFILE_THIRD_ACCESSES = 'GET_PROFILE_THIRD_ACCESSES'

SHARE_TYPE_EDIT = 0
SHARE_TYPE_VIEW = 1
SHARE_TYPE_PROPERTY = 2

#endregion
