pyside6-rcc finances/src/ui/imgs/resource.qrc -o finances/src/ui/auto/resource_rc.py
pyside6-uic finances/src/ui/CreateAccountForm.ui -o finances/src/ui/auto/ui_CreateAccountForm.py
pyside6-uic finances/src/ui/LoginForm.ui -o finances/src/ui/auto/ui_LoginForm.py
pyside6-uic finances/src/ui/LoginPage.ui -o finances/src/ui/auto/ui_LoginPage.py
pyside6-uic finances/src/ui/MainPage.ui -o finances/src/ui/auto/ui_MainPage.py
pyside6-uic finances/src/ui/ConfigForm.ui -o finances/src/ui/auto/ui_ConfigForm.py
pyside6-uic finances/src/ui/TableForm.ui -o finances/src/ui/auto/ui_TableForm.py
pyside6-uic finances/src/ui/RegForm.ui -o finances/src/ui/auto/ui_RegForm.py
pyside6-uic finances/src/ui/CardAccountForm.ui -o finances/src/ui/auto/ui_CardAccountForm.py